### PR TITLE
fix(shortcuts): resolve issue with keyboard navigation after slide na…

### LINKED ISSUE #840: '<-' and '->' on keyboard doesn't work if focus on '<-'/'->' buttons

### PR DESCRIPTION
**Pull request by antkiewicz**
…v button focus closes #840

### CODE REVIEW

File: libs/slides/src/lib/shortcuts/shortcuts.directive.ts [hunk 1]
```diff
@@ -1,25 +1,29 @@
...
 import { SlidesDeckComponent } from '../deck/deck.component';
+import { SlidesArrowsComponent } from '../arrows/slides-arrows.component';
 import { FullScreenModeService } from '@codelab/utils';
 
 @Directive({
   selector: '[slideShortcuts]'
 })
 export class ShortcutsDirective {
+
+  @ContentChild(SlidesArrowsComponent, { static: false }) private arrows: SlidesArrowsComponent;
```
Comment (kirjs) [inline libs/slides/src/lib/shortcuts/shortcuts.directive.ts]: Hm, instead of requiring arrows and being tightly bound to them, can we just have an attribute on the DOM element and check if target has this dom element?

I can totally forsee having a nicer looking arrows component, or wanting to have this functionality for progress bar

File: libs/slides/src/lib/shortcuts/shortcuts.directive.ts [hunk 2]
```diff
@@ -31,4 +32,21 @@ export class ShortcutsDirective {
...
   }
+
+  private canNavigate(target: HTMLElement) {
+    return target === document.body || this.isFromContext(target);
+  }
+
+  private isFromContext(target: HTMLElement) {
+    let parent = target;
+
+    while (parent && parent.nodeName !== 'BODY') {
```
Comment (NothingEverHappens) [inline libs/slides/src/lib/shortcuts/shortcuts.directive.ts]: drop parent.nodeName !== 'BODY'
